import { UserInterest } from '../models/interest';

// prettier-ignore
export const categoryMap: { [category: string]: UserInterest[] | undefined } = {
    "/art and entertainment/books and literature/best-sellers": undefined,
    "/art and entertainment/books and literature/children's books": undefined,
    "/art and entertainment/books and literature/e-books": undefined,
    "/art and entertainment/books and literature/fan fiction": undefined,
    "/art and entertainment/books and literature/magazines": undefined,
    "/art and entertainment/books and literature/mythology": undefined,
    "/art and entertainment/books and literature/non-fiction": undefined,
    "/art and entertainment/books and literature/poetry": undefined,
    "/art and entertainment/books and literature/reference books": undefined,
    "/art and entertainment/books and literature/romance novels": undefined,
    "/art and entertainment/books and literature/science fiction": undefined,
    "/art and entertainment/books and literature/textbooks": undefined,
    "/art and entertainment/books and literature": undefined,
    "/art and entertainment/celebrity fan and gossip": undefined,
    "/art and entertainment/comics and animation/anime and manga": undefined,
    "/art and entertainment/comics and animation/cartoons": undefined,
    "/art and entertainment/comics and animation/comics": undefined,
    "/art and entertainment/dance/ballet": undefined,
    "/art and entertainment/dance/ballroom dance": undefined,
    "/art and entertainment/dance/belly dance": undefined,
    "/art and entertainment/dance/modern dance": undefined,
    "/art and entertainment/dance/pole dancing": undefined,
    "/art and entertainment/dance": undefined,
    "/art and entertainment/humor": undefined,
    "/art and entertainment/movies/film festivals and awards": undefined,
    "/art and entertainment/movies and tv/action": undefined,
    "/art and entertainment/movies and tv/animated": undefined,
    "/art and entertainment/movies and tv/bollywood": undefined,
    "/art and entertainment/movies and tv/children's": undefined,
    "/art and entertainment/movies and tv/classics/silent films": undefined,
    "/art and entertainment/movies and tv/classics": undefined,
    "/art and entertainment/movies and tv/comedies": undefined,
    "/art and entertainment/movies and tv/cult classics": undefined,
    "/art and entertainment/movies and tv/documentaries": undefined,
    "/art and entertainment/movies and tv/dramas": undefined,
    "/art and entertainment/movies and tv/horror": undefined,
    "/art and entertainment/movies and tv/independent": undefined,
    "/art and entertainment/movies and tv/movies/reviews": undefined,
    "/art and entertainment/movies and tv/movies/trailers": undefined,
    "/art and entertainment/movies and tv/movies": undefined,
    "/art and entertainment/movies and tv/reality": undefined,
    "/art and entertainment/movies and tv/romantic comedies": undefined,
    "/art and entertainment/movies and tv/talk shows": undefined,
    "/art and entertainment/movies and tv/television": undefined,
    "/art and entertainment/movies and tv/thrillers": undefined,
    "/art and entertainment/movies and tv/westerns": undefined,
    "/art and entertainment/music/music genres/blues": ['party'],
    "/art and entertainment/music/music genres/classical music": ['party'],
    "/art and entertainment/music/music genres/country music": ['party'],
    "/art and entertainment/music/music genres/easy listening": undefined,
    "/art and entertainment/music/music genres/electronic music": ['party'],
    "/art and entertainment/music/music genres/folk music": ['party'],
    "/art and entertainment/music/music genres/hip hop": ['party'],
    "/art and entertainment/music/music genres/jazz": ['party'],
    "/art and entertainment/music/music genres/opera": undefined,
    "/art and entertainment/music/music genres/pop music": ['party'],
    "/art and entertainment/music/music genres/punk": ['party'],
    "/art and entertainment/music/music genres/religious music": undefined,
    "/art and entertainment/music/music genres/rock music": ['party'],
    "/art and entertainment/music/music genres/ska": ['party'],
    "/art and entertainment/music/music genres/soul music": ['party'],
    "/art and entertainment/music/music genres/soundtracks": ['party'],
    "/art and entertainment/music/music genres/world music": ['party'],
    "/art and entertainment/music/music reference/music composition and theory": undefined,
    "/art and entertainment/music/music reference/sheet music": undefined,
    "/art and entertainment/music/musical instruments/drums": ['party'],
    "/art and entertainment/music/musical instruments/guitars": ['party'],
    "/art and entertainment/music/musical instruments/pianos": ['party'],
    "/art and entertainment/music/musical instruments": ['party'],
    "/art and entertainment/music/recording industry/music awards": ['party'],
    "/art and entertainment/music/recording industry/record labels": ['party'],
    "/art and entertainment/music/recording industry": ['party'],
    "/art and entertainment/music/singing": ['party'],
    "/art and entertainment/music": ['party'],
    "/art and entertainment/radio/podcasts": undefined,
    "/art and entertainment/radio/radio programs": undefined,
    "/art and entertainment/radio/talk radio": undefined,
    "/art and entertainment/radio": undefined,
    "/art and entertainment/shows and events/beauty contest": undefined,
    "/art and entertainment/shows and events/circus": undefined,
    "/art and entertainment/shows and events/classical concert": undefined,
    "/art and entertainment/shows and events/concert": undefined,
    "/art and entertainment/shows and events/conference": undefined,
    "/art and entertainment/shows and events/exhibition": undefined,
    "/art and entertainment/shows and events/fair": undefined,
    "/art and entertainment/shows and events/festival": ['party'],
    "/art and entertainment/shows and events/sports event": undefined,
    "/art and entertainment/theatre/theatre awards": undefined,
    "/art and entertainment/theatre/theatre companies": undefined,
    "/art and entertainment/theatre": undefined,
    "/art and entertainment/visual art and design/architecture": ['architecture'],
    "/art and entertainment/visual art and design/art and craft supplies": ['architecture','museum'],
    "/art and entertainment/visual art and design/art museums and galleries": ['museum'],
    "/art and entertainment/visual art and design/arts education": undefined,
    "/art and entertainment/visual art and design/design/graphic design": undefined,
    "/art and entertainment/visual art and design/design/industrial and product design": ['architecture','museum'],
    "/art and entertainment/visual art and design/design/interior design": undefined,
    "/art and entertainment/visual art and design/design": undefined,
    "/art and entertainment/visual art and design/digital art": ['museum'],
    "/art and entertainment/visual art and design/drawing": ['museum'],
    "/art and entertainment/visual art and design/painting": ['museum'],
    "/art and entertainment/visual art and design/performance art": undefined,
    "/art and entertainment/visual art and design/restoration": ['architecture'],
    "/art and entertainment/visual art and design/sculpture": ['architecture'],
    "/art and entertainment/visual art and design": ['architecture','museum'],
    "/art and entertainment": ['architecture','museum'],
    "/automotive and vehicles/auto parts": undefined,
    "/automotive and vehicles/auto repair": undefined,
    "/automotive and vehicles/bicycles and accessories/mountain bikes": undefined,
    "/automotive and vehicles/bicycles and accessories": undefined,
    "/automotive and vehicles/boats and watercraft": undefined,
    "/automotive and vehicles/buying and selling cars": undefined,
    "/automotive and vehicles/campers and rvs": undefined,
    "/automotive and vehicles/cars/car culture": undefined,
    "/automotive and vehicles/cars/car industry": undefined,
    "/automotive and vehicles/cars/convertible": undefined,
    "/automotive and vehicles/cars/coupe": undefined,
    "/automotive and vehicles/cars/crossover": undefined,
    "/automotive and vehicles/cars/diesel": undefined,
    "/automotive and vehicles/cars/hatchback": undefined,
    "/automotive and vehicles/cars/hybrid": undefined,
    "/automotive and vehicles/cars/luxury": undefined,
    "/automotive and vehicles/cars/performance vehicles": undefined,
    "/automotive and vehicles/cars/sedan": undefined,
    "/automotive and vehicles/cars/vintage cars": undefined,
    "/automotive and vehicles/cars/wagon": undefined,
    "/automotive and vehicles/cars": undefined,
    "/automotive and vehicles/certified pre-owned": undefined,
    "/automotive and vehicles/commercial vehicles": undefined,
    "/automotive and vehicles/electric vehicles": undefined,
    "/automotive and vehicles/minivan": undefined,
    "/automotive and vehicles/motor shows": undefined,
    "/automotive and vehicles/motorcycles": undefined,
    "/automotive and vehicles/off-road vehicles": undefined,
    "/automotive and vehicles/road-side assistance": undefined,
    "/automotive and vehicles/scooters and mopeds": undefined,
    "/automotive and vehicles/trucks and suvs/pickup trucks": undefined,
    "/automotive and vehicles/trucks and suvs/suvs": undefined,
    "/automotive and vehicles/trucks and suvs/truck accessories": undefined,
    "/automotive and vehicles/vehicle brands/acura": undefined,
    "/automotive and vehicles/vehicle brands/alfa romeo": undefined,
    "/automotive and vehicles/vehicle brands/audi": undefined,
    "/automotive and vehicles/vehicle brands/bentley": undefined,
    "/automotive and vehicles/vehicle brands/buick": undefined,
    "/automotive and vehicles/vehicle brands/cadillac": undefined,
    "/automotive and vehicles/vehicle brands/chevrolet": undefined,
    "/automotive and vehicles/vehicle brands/chrysler": undefined,
    "/automotive and vehicles/vehicle brands/ferrari": undefined,
    "/automotive and vehicles/vehicle brands/fiat": undefined,
    "/automotive and vehicles/vehicle brands/ford": undefined,
    "/automotive and vehicles/vehicle brands/honda": undefined,
    "/automotive and vehicles/vehicle brands/hyundai": undefined,
    "/automotive and vehicles/vehicle brands/isuzu": undefined,
    "/automotive and vehicles/vehicle brands/jeep": undefined,
    "/automotive and vehicles/vehicle brands/kia": undefined,
    "/automotive and vehicles/vehicle brands/lamborghini": undefined,
    "/automotive and vehicles/vehicle brands/land rover": undefined,
    "/automotive and vehicles/vehicle brands/maserati": undefined,
    "/automotive and vehicles/vehicle brands/mazda": undefined,
    "/automotive and vehicles/vehicle brands/mercedes-benz": undefined,
    "/automotive and vehicles/vehicle brands/mitsubishi": undefined,
    "/automotive and vehicles/vehicle brands/nissan/infiniti": undefined,
    "/automotive and vehicles/vehicle brands/nissan": undefined,
    "/automotive and vehicles/vehicle brands/peugeot": undefined,
    "/automotive and vehicles/vehicle brands/pontiac": undefined,
    "/automotive and vehicles/vehicle brands/porsche": undefined,
    "/automotive and vehicles/vehicle brands/rolls-royce": undefined,
    "/automotive and vehicles/vehicle brands/saab": undefined,
    "/automotive and vehicles/vehicle brands/scion": undefined,
    "/automotive and vehicles/vehicle brands/subaru": undefined,
    "/automotive and vehicles/vehicle brands/suzuki": undefined,
    "/automotive and vehicles/vehicle brands/toyota": undefined,
    "/automotive and vehicles/vehicle brands/volkswagen": undefined,
    "/automotive and vehicles/vehicle brands/volvo": undefined,
    "/automotive and vehicles/vehicle rental": undefined,
    "/automotive and vehicles": undefined,
    "/business and industrial/advertising and marketing/advertising": undefined,
    "/business and industrial/advertising and marketing/brand management": undefined,
    "/business and industrial/advertising and marketing/marketing": undefined,
    "/business and industrial/advertising and marketing/public relations": undefined,
    "/business and industrial/advertising and marketing/telemarketing": undefined,
    "/business and industrial/aerospace and defense/defense industry": undefined,
    "/business and industrial/aerospace and defense/space technology": undefined,
    "/business and industrial/aerospace and defense": undefined,
    "/business and industrial/agriculture and forestry/agriculture": ['flowers'],
    "/business and industrial/agriculture and forestry/aquaculture": undefined,
    "/business and industrial/agriculture and forestry/crops and seed": ['flowers'],
    "/business and industrial/agriculture and forestry/farms and ranches": ['flowers'],
    "/business and industrial/agriculture and forestry/food production": undefined,
    "/business and industrial/agriculture and forestry/forestry": undefined,
    "/business and industrial/agriculture and forestry/horticulture": undefined,
    "/business and industrial/agriculture and forestry/livestock": undefined,
    "/business and industrial/agriculture and forestry/organic farming": undefined,
    "/business and industrial/automation/robotics": undefined,
    "/business and industrial/biomedical": undefined,
    "/business and industrial/business news": undefined,
    "/business and industrial/business operations/business plans": undefined,
    "/business and industrial/business operations/human resources/compensation and benefits": undefined,
    "/business and industrial/business operations/human resources/payroll services": undefined,
    "/business and industrial/business operations/human resources": undefined,
    "/business and industrial/business operations/management/business process": undefined,
    "/business and industrial/business operations/management/project management": undefined,
    "/business and industrial/business operations/management/supply chain management": undefined,
    "/business and industrial/business operations": undefined,
    "/business and industrial/business software": undefined,
    "/business and industrial/chemicals industry/adhesives": undefined,
    "/business and industrial/chemicals industry/cleaning agents": undefined,
    "/business and industrial/chemicals industry/dyes and pigments": undefined,
    "/business and industrial/chemicals industry/plastics and polymers": undefined,
    "/business and industrial/chemicals industry": undefined,
    "/business and industrial/company/annual report": undefined,
    "/business and industrial/company/bankruptcy": undefined,
    "/business and industrial/company/earnings": undefined,
    "/business and industrial/company/joint venture": undefined,
    "/business and industrial/company/merger and acquisition": undefined,
    "/business and industrial/construction": undefined,
    "/business and industrial/energy/coal": undefined,
    "/business and industrial/energy/electricity": undefined,
    "/business and industrial/energy/natural gas": undefined,
    "/business and industrial/energy/nuclear power/nuclear accident": undefined,
    "/business and industrial/energy/nuclear power": undefined,
    "/business and industrial/energy/oil/diesel fuel": undefined,
    "/business and industrial/energy/oil/oil and gas prices": undefined,
    "/business and industrial/energy/oil/oil company": undefined,
    "/business and industrial/energy/oil": undefined,
    "/business and industrial/energy/renewable energy/biofuel": undefined,
    "/business and industrial/energy/renewable energy/fuel cell": undefined,
    "/business and industrial/energy/renewable energy/geothermal energy": undefined,
    "/business and industrial/energy/renewable energy/hydroelectric energy": undefined,
    "/business and industrial/energy/renewable energy/solar energy": undefined,
    "/business and industrial/energy/renewable energy/wind energy": undefined,
    "/business and industrial/energy/renewable energy": undefined,
    "/business and industrial/fashion industry": undefined,
    "/business and industrial/food industry": undefined,
    "/business and industrial/green solutions": undefined,
    "/business and industrial/hospitality industry/event planning": undefined,
    "/business and industrial/hospitality industry/food service": ['food'],
    "/business and industrial/hospitality industry": undefined,
    "/business and industrial/iron and steel industry": undefined,
    "/business and industrial/logistics/air freight": undefined,
    "/business and industrial/logistics/freight train": undefined,
    "/business and industrial/logistics": undefined,
    "/business and industrial/manufacturing": undefined,
    "/business and industrial/metals": undefined,
    "/business and industrial/mining industry": undefined,
    "/business and industrial/paper industry": undefined,
    "/business and industrial/pharmaceutical industry": undefined,
    "/business and industrial/publishing": undefined,
    "/business and industrial/record company": undefined,
    "/business and industrial/shipbuilding": undefined,
    "/business and industrial/tanning": undefined,
    "/business and industrial/textile industry": undefined,
    "/business and industrial/war industry/weaponry": undefined,
    "/business and industrial": undefined,
    "/careers/career advice": undefined,
    "/careers/career planning": undefined,
    "/careers/job fairs": undefined,
    "/careers/job search": undefined,
    "/careers/nursing": undefined,
    "/careers/resume writing and advice": undefined,
    "/careers/telecommuting": undefined,
    "/careers/u.s. military": undefined,
    "/careers": undefined,
    "/education/adult education": undefined,
    "/education/alumni and reunions": undefined,
    "/education/art history": ['museum'],
    "/education/distance learning": undefined,
    "/education/english as a second language": undefined,
    "/education/grade school": undefined,
    "/education/graduate school/college": undefined,
    "/education/graduate school/college administration": undefined,
    "/education/graduate school/college life": undefined,
    "/education/graduate school": undefined,
    "/education/high school": undefined,
    "/education/homeschooling": undefined,
    "/education/homework and study tips": undefined,
    "/education/language learning": undefined,
    "/education/school/private school": undefined,
    "/education/school": undefined,
    "/education/special education": undefined,
    "/education/studying business": undefined,
    "/education/teaching and classroom resources/lesson plans": undefined,
    "/education/teaching and classroom resources/school supplies": undefined,
    "/education": undefined,
    "/family and parenting/adoption": undefined,
    "/family and parenting/babies and toddlers/baby clothes": undefined,
    "/family and parenting/babies and toddlers/baby food": undefined,
    "/family and parenting/babies and toddlers": undefined,
    "/family and parenting/children/daycare and preschool": undefined,
    "/family and parenting/children": undefined,
    "/family and parenting/eldercare": undefined,
    "/family and parenting/motherhood/artificial insemination": undefined,
    "/family and parenting/motherhood/pregnancy": undefined,
    "/family and parenting/motherhood": undefined,
    "/family and parenting/parenting teens": undefined,
    "/family and parenting/special needs kids": undefined,
    "/family and parenting": undefined,
    "/finance/accounting and auditing/billing and invoicing": undefined,
    "/finance/accounting and auditing/bookkeeping": undefined,
    "/finance/accounting and auditing/tax preparation and planning": undefined,
    "/finance/accounting and auditing": undefined,
    "/finance/bank/atms": undefined,
    "/finance/bank/bank account": undefined,
    "/finance/bank/checks": undefined,
    "/finance/bank": undefined,
    "/finance/financial news": undefined,
    "/finance/grants, scholarships and financial aid/financial aid": undefined,
    "/finance/grants, scholarships and financial aid/government grants": undefined,
    "/finance/grants, scholarships and financial aid/scholarships": undefined,
    "/finance/investing/beginning investing": undefined,
    "/finance/investing/brokerages": undefined,
    "/finance/investing/day trading": undefined,
    "/finance/investing/funds/exchange traded funds": undefined,
    "/finance/investing/funds/hedge fund": undefined,
    "/finance/investing/funds/mutual funds": undefined,
    "/finance/investing/futures trading": undefined,
    "/finance/investing/options": undefined,
    "/finance/investing/portfolio": undefined,
    "/finance/investing/stocks": undefined,
    "/finance/investing/venture capital": undefined,
    "/finance/investing": undefined,
    "/finance/personal finance/debt management": undefined,
    "/finance/personal finance/financial planning/asset and portfolio management": undefined,
    "/finance/personal finance/financial planning/estate planning": undefined,
    "/finance/personal finance/financial planning/retirement and pension": undefined,
    "/finance/personal finance/financial planning": undefined,
    "/finance/personal finance/insurance/car insurance": undefined,
    "/finance/personal finance/insurance/health insurance": undefined,
    "/finance/personal finance/insurance/homeowners insurance": undefined,
    "/finance/personal finance/insurance/life insurance": undefined,
    "/finance/personal finance/insurance/travel insurance": undefined,
    "/finance/personal finance/insurance/vehicle insurance": undefined,
    "/finance/personal finance/insurance": undefined,
    "/finance/personal finance/lending/credit cards": undefined,
    "/finance/personal finance/lending/home financing": undefined,
    "/finance/personal finance/lending/personal loans": undefined,
    "/finance/personal finance/lending/student loans": undefined,
    "/finance/personal finance/lending/vehicle financing": undefined,
    "/finance/personal finance/saving": undefined,
    "/finance": undefined,
    "/food and drink/barbecues and grilling": undefined,
    "/food and drink/beverages/alcoholic beverages/cocktails and beer": ['party'],
    "/food and drink/beverages/alcoholic beverages/wine": ['party'],
    "/food and drink/beverages/non alcoholic beverages/bottled water": undefined,
    "/food and drink/beverages/non alcoholic beverages/coffee and tea": undefined,
    "/food and drink/beverages/non alcoholic beverages/soft drinks": undefined,
    "/food and drink/beverages": ['food'],
    "/food and drink/cuisines/american cuisine": ['food'],
    "/food and drink/cuisines/chinese cuisine": ['food'],
    "/food and drink/cuisines/french cuisine": ['food'],
    "/food and drink/cuisines/indian cuisine": ['food'],
    "/food and drink/cuisines/italian cuisine": ['food'],
    "/food and drink/cuisines/japanese cuisine": ['food'],
    "/food and drink/cuisines/mexican cuisine": ['food'],
    "/food and drink/cuisines/regional cuisine": ['food'],
    "/food and drink/desserts and baking": ['food'],
    "/food and drink/dining out": ['food'],
    "/food and drink/food/baked goods": ['food'],
    "/food and drink/food/breakfast foods": undefined,
    "/food and drink/food/candy and sweets": undefined,
    "/food and drink/food/condiments and dressings": undefined,
    "/food and drink/food/fast food": ['food'],
    "/food and drink/food/frozen food": undefined,
    "/food and drink/food/fruits and vegetables": undefined,
    "/food and drink/food/grains and pasta": undefined,
    "/food and drink/food/herbs and spices": undefined,
    "/food and drink/food/salads": undefined,
    "/food and drink/food/snack foods": ['food'],
    "/food and drink/food allergies": undefined,
    "/food and drink/food and grocery retailers/bakeries": undefined,
    "/food and drink/food and grocery retailers/butchers": undefined,
    "/food and drink/food and grocery retailers/convenience stores": undefined,
    "/food and drink/food and grocery retailers/grocery stores": undefined,
    "/food and drink/gastronomy/slow food": undefined,
    "/food and drink/gastronomy": undefined,
    "/food and drink/health and lowfat cooking": undefined,
    "/food and drink/healthy eating": ['food'],
    "/food and drink/kosher food": undefined,
    "/food and drink/vegan": undefined,
    "/food and drink/vegetarian": undefined,
    "/food and drink": ['food'],
    "/health and fitness/addiction/alcoholism": ['party','drugs'],
    "/health and fitness/addiction/smoking addiction": ['drugs'],
    "/health and fitness/addiction/substance abuse": ['drugs'],
    "/health and fitness/addiction": ['drugs'],
    "/health and fitness/aging": undefined,
    "/health and fitness/alternative medicine/herbs for health": undefined,
    "/health and fitness/alternative medicine/holistic healing": undefined,
    "/health and fitness/alternative medicine/homeopathy": undefined,
    "/health and fitness/alternative medicine": undefined,
    "/health and fitness/dental care": undefined,
    "/health and fitness/disease/aids and hiv": undefined,
    "/health and fitness/disease/allergies": undefined,
    "/health and fitness/disease/arthritis": undefined,
    "/health and fitness/disease/asthma": undefined,
    "/health and fitness/disease/autism and pdd": undefined,
    "/health and fitness/disease/cancer/brain tumor": undefined,
    "/health and fitness/disease/cancer": undefined,
    "/health and fitness/disease/cholesterol": undefined,
    "/health and fitness/disease/chronic fatigue syndrome": undefined,
    "/health and fitness/disease/chronic pain": undefined,
    "/health and fitness/disease/cold and flu": undefined,
    "/health and fitness/disease/deafness": undefined,
    "/health and fitness/disease/diabetes": undefined,
    "/health and fitness/disease/epidemic": undefined,
    "/health and fitness/disease/epilepsy": undefined,
    "/health and fitness/disease/gerd and acid reflux": undefined,
    "/health and fitness/disease/headaches and migraines": undefined,
    "/health and fitness/disease/heart disease": undefined,
    "/health and fitness/disease/ibs and crohn's disease": undefined,
    "/health and fitness/disease/incontinence": undefined,
    "/health and fitness/disease/infertility": undefined,
    "/health and fitness/disease/thyroid disease": undefined,
    "/health and fitness/disease": undefined,
    "/health and fitness/disorders/mental disorder/a.d.d.": undefined,
    "/health and fitness/disorders/mental disorder/bipolar disorder": undefined,
    "/health and fitness/disorders/mental disorder/depression": undefined,
    "/health and fitness/disorders/mental disorder/panic and anxiety": undefined,
    "/health and fitness/disorders/mental disorder": undefined,
    "/health and fitness/disorders/sleep disorders": undefined,
    "/health and fitness/disorders": undefined,
    "/health and fitness/drugs": ['drugs'],
    "/health and fitness/exercise": undefined,
    "/health and fitness/incest and abuse support": undefined,
    "/health and fitness/men's health": undefined,
    "/health and fitness/nutrition": undefined,
    "/health and fitness/sexuality": undefined,
    "/health and fitness/sports medicine": undefined,
    "/health and fitness/therapy/physical therapy": undefined,
    "/health and fitness/therapy": undefined,
    "/health and fitness/weight loss": undefined,
    "/health and fitness/women's health": undefined,
    "/health and fitness": undefined,
    "/hobbies and interests/art and technology": undefined,
    "/hobbies and interests/arts and crafts/beadwork": undefined,
    "/hobbies and interests/arts and crafts/candle and soap making": undefined,
    "/hobbies and interests/arts and crafts/crochet": undefined,
    "/hobbies and interests/arts and crafts/jewelry making": undefined,
    "/hobbies and interests/arts and crafts/knitting": undefined,
    "/hobbies and interests/arts and crafts/photography": ['museum'],
    "/hobbies and interests/arts and crafts/pottery": undefined,
    "/hobbies and interests/arts and crafts/watchmaking": undefined,
    "/hobbies and interests/arts and crafts/woodworking": undefined,
    "/hobbies and interests/arts and crafts": ['museum'],
    "/hobbies and interests/astrology": undefined,
    "/hobbies and interests/birdwatching": undefined,
    "/hobbies and interests/cigars": ['drugs'],
    "/hobbies and interests/collecting/stamps and coins": undefined,
    "/hobbies and interests/collecting": undefined,
    "/hobbies and interests/games/board games and puzzles": undefined,
    "/hobbies and interests/games/card games": undefined,
    "/hobbies and interests/games/chess": undefined,
    "/hobbies and interests/games/gambling": undefined,
    "/hobbies and interests/games/lottery": undefined,
    "/hobbies and interests/games/role playing games": undefined,
    "/hobbies and interests/games/video and computer games": undefined,
    "/hobbies and interests/getting published/freelance writing": undefined,
    "/hobbies and interests/getting published/screenwriting": undefined,
    "/hobbies and interests/getting published": undefined,
    "/hobbies and interests/guitar": undefined,
    "/hobbies and interests/home recording": undefined,
    "/hobbies and interests/inventors and patents": undefined,
    "/hobbies and interests/magic and illusion": undefined,
    "/hobbies and interests/needlework": undefined,
    "/hobbies and interests/paranormal phenomena/occult": undefined,
    "/hobbies and interests/paranormal phenomena/parapsychology": undefined,
    "/hobbies and interests/paranormal phenomena": undefined,
    "/hobbies and interests/reading": undefined,
    "/hobbies and interests/scrapbooking": undefined,
    "/hobbies and interests": undefined,
    "/home and garden/appliances/dishwashers": undefined,
    "/home and garden/appliances/microwaves": undefined,
    "/home and garden/appliances/refrigerators and freezers": undefined,
    "/home and garden/appliances/small appliances/blenders": undefined,
    "/home and garden/appliances/small appliances/coffee maker": undefined,
    "/home and garden/appliances/small appliances/food processors": undefined,
    "/home and garden/appliances/small appliances/toasters and toaster ovens": undefined,
    "/home and garden/appliances/stoves": undefined,
    "/home and garden/appliances": undefined,
    "/home and garden/bed and bath/bathroom": undefined,
    "/home and garden/bed and bath/bedroom/bedding and bed linens": undefined,
    "/home and garden/bed and bath/bedroom/beds and headboards": undefined,
    "/home and garden/bed and bath/bedroom/mattresses": undefined,
    "/home and garden/bed and bath/bedroom": undefined,
    "/home and garden/environmental safety": undefined,
    "/home and garden/gardening and landscaping/gardening": undefined,
    "/home and garden/gardening and landscaping/landscaping": undefined,
    "/home and garden/gardening and landscaping/yard and patio": undefined,
    "/home and garden/home furnishings/lamps and lighting": undefined,
    "/home and garden/home furnishings/rugs and carpets": undefined,
    "/home and garden/home furnishings/sofas and chairs": undefined,
    "/home and garden/home furnishings": undefined,
    "/home and garden/home improvement and repair/house painting and finishing": undefined,
    "/home and garden/home improvement and repair/locks and locksmiths": undefined,
    "/home and garden/home improvement and repair/plumbing": undefined,
    "/home and garden/home improvement and repair/power tools": undefined,
    "/home and garden/home improvement and repair/roofing": undefined,
    "/home and garden/home improvement and repair": undefined,
    "/home and garden/interior decorating": undefined,
    "/home and garden/laundry": undefined,
    "/home and garden/luxury homes": undefined,
    "/home and garden/nursery and playroom": undefined,
    "/home and garden/pest control": undefined,
    "/home and garden/remodeling and construction": undefined,
    "/home and garden": undefined,
    "/law, govt and politics/armed forces/air force": undefined,
    "/law, govt and politics/armed forces/army": undefined,
    "/law, govt and politics/armed forces/marines": undefined,
    "/law, govt and politics/armed forces/navy": undefined,
    "/law, govt and politics/armed forces/veterans": undefined,
    "/law, govt and politics/commentary": undefined,
    "/law, govt and politics/espionage and intelligence/secret service": undefined,
    "/law, govt and politics/espionage and intelligence/surveillance": undefined,
    "/law, govt and politics/espionage and intelligence/terrorism": undefined,
    "/law, govt and politics/espionage and intelligence": undefined,
    "/law, govt and politics/government/courts and judiciary": undefined,
    "/law, govt and politics/government/embassies and consulates": undefined,
    "/law, govt and politics/government/executive branch": undefined,
    "/law, govt and politics/government/government agencies": undefined,
    "/law, govt and politics/government/government contracting and procurement": undefined,
    "/law, govt and politics/government/heads of state": undefined,
    "/law, govt and politics/government/legislative": undefined,
    "/law, govt and politics/government/parliament": undefined,
    "/law, govt and politics/government/state and local government": undefined,
    "/law, govt and politics/government": undefined,
    "/law, govt and politics/immigration": undefined,
    "/law, govt and politics/law enforcement/coast guard": undefined,
    "/law, govt and politics/law enforcement/fire department": undefined,
    "/law, govt and politics/law enforcement/highway patrol": undefined,
    "/law, govt and politics/law enforcement/police": undefined,
    "/law, govt and politics/law enforcement": undefined,
    "/law, govt and politics/legal issues/civil law/copyright": undefined,
    "/law, govt and politics/legal issues/civil law": undefined,
    "/law, govt and politics/legal issues/civil rights": undefined,
    "/law, govt and politics/legal issues/civil rights/privacy": undefined,
    "/law, govt and politics/legal issues/criminal law": undefined,
    "/law, govt and politics/legal issues/death penalty": undefined,
    "/law, govt and politics/legal issues/human rights": undefined,
    "/law, govt and politics/legal issues/international law": undefined,
    "/law, govt and politics/legal issues/legislation/building laws": undefined,
    "/law, govt and politics/legal issues/legislation/education laws": undefined,
    "/law, govt and politics/legal issues/legislation/family laws": undefined,
    "/law, govt and politics/legal issues/legislation/health care laws": undefined,
    "/law, govt and politics/legal issues/legislation/immigration laws": undefined,
    "/law, govt and politics/legal issues/legislation/tax laws": undefined,
    "/law, govt and politics/legal issues/legislation": undefined,
    "/law, govt and politics/legal issues": undefined,
    "/law, govt and politics/politics/domestic policy": undefined,
    "/law, govt and politics/politics/elections/local elections": undefined,
    "/law, govt and politics/politics/elections/presidential elections": undefined,
    "/law, govt and politics/politics/elections/referendums": undefined,
    "/law, govt and politics/politics/elections": undefined,
    "/law, govt and politics/politics/foreign policy": undefined,
    "/law, govt and politics/politics/lobbying": undefined,
    "/law, govt and politics/politics/political parties": undefined,
    "/law, govt and politics/politics": undefined,
    "/law, govt and politics": undefined,
    "/news/international news": undefined,
    "/news/local news": undefined,
    "/news/national news": undefined,
    "/news": undefined,
    "/pets/animal welfare": undefined,
    "/pets/aquariums": undefined,
    "/pets/birds": undefined,
    "/pets/cats": undefined,
    "/pets/dogs": undefined,
    "/pets/large animals": undefined,
    "/pets/reptiles": undefined,
    "/pets/zoo": undefined,
    "/pets": undefined,
    "/real estate/apartments": undefined,
    "/real estate/architects": ['architecture'],
    "/real estate/buying and selling homes": undefined,
    "/real estate/low income housing": undefined,
    "/real estate": undefined,
    "/religion and spirituality/alternative religions/pagan and wiccan": undefined,
    "/religion and spirituality/atheism and agnosticism": undefined,
    "/religion and spirituality/buddhism": undefined,
    "/religion and spirituality/christianity/catholicism": undefined,
    "/religion and spirituality/christianity/latter-day saints": undefined,
    "/religion and spirituality/christianity/orthodoxy": undefined,
    "/religion and spirituality/christianity/protestantism": undefined,
    "/religion and spirituality/christianity": undefined,
    "/religion and spirituality/hinduism": undefined,
    "/religion and spirituality/islam/islamic fundamentalism": undefined,
    "/religion and spirituality/islam": undefined,
    "/religion and spirituality/judaism": undefined,
    "/religion and spirituality": undefined,
    "/science/biology/biotechnology": undefined,
    "/science/biology/botany": undefined,
    "/science/biology/breeding": undefined,
    "/science/biology/cytology": undefined,
    "/science/biology/marine biology": undefined,
    "/science/biology/molecular biology": undefined,
    "/science/biology/zoology/endangered species": undefined,
    "/science/biology/zoology/entomology": undefined,
    "/science/biology/zoology/ornithology": undefined,
    "/science/biology/zoology": undefined,
    "/science/biology": undefined,
    "/science/chemistry/organic chemistry": undefined,
    "/science/chemistry": undefined,
    "/science/computer science/artificial intelligence": undefined,
    "/science/computer science/cryptography": undefined,
    "/science/computer science/distributed systems": undefined,
    "/science/computer science/information science": undefined,
    "/science/computer science/software engineering": undefined,
    "/science/computer science": undefined,
    "/science/ecology/environmental disaster": undefined,
    "/science/ecology/pollution": undefined,
    "/science/ecology/waste management/recycling": undefined,
    "/science/ecology/waste management/waste disposal": undefined,
    "/science/ecology": undefined,
    "/science/engineering": undefined,
    "/science/geography/cartography": undefined,
    "/science/geography/topography": undefined,
    "/science/geography": undefined,
    "/science/geology/mineralogy": undefined,
    "/science/geology/seismology/earthquakes": undefined,
    "/science/geology/volcanology/volcanic eruptions": undefined,
    "/science/geology": undefined,
    "/science/mathematics/algebra": undefined,
    "/science/mathematics/arithmetic": undefined,
    "/science/mathematics/geometry": undefined,
    "/science/mathematics/statistics": undefined,
    "/science/mathematics": undefined,
    "/science/medicine/cardiology": undefined,
    "/science/medicine/dermatology": undefined,
    "/science/medicine/embryology": undefined,
    "/science/medicine/genetics": undefined,
    "/science/medicine/immunology": undefined,
    "/science/medicine/medical research": undefined,
    "/science/medicine/oncology": undefined,
    "/science/medicine/orthopedics": undefined,
    "/science/medicine/pediatrics": undefined,
    "/science/medicine/pharmacology": undefined,
    "/science/medicine/physiology": undefined,
    "/science/medicine/psychology and psychiatry/psychoanalysis": undefined,
    "/science/medicine/psychology and psychiatry": undefined,
    "/science/medicine/surgery/cosmetic surgery": undefined,
    "/science/medicine/surgery/transplants": undefined,
    "/science/medicine/surgery": undefined,
    "/science/medicine/veterinary medicine": undefined,
    "/science/medicine": undefined,
    "/science/physics/atomic physics": undefined,
    "/science/physics/astrophysics": undefined,
    "/science/physics/electromagnetism": undefined,
    "/science/physics/hydraulics": undefined,
    "/science/physics/nanotechnology": undefined,
    "/science/physics/optics": undefined,
    "/science/physics/space and astronomy": undefined,
    "/science/physics/thermodynamics": undefined,
    "/science/physics": undefined,
    "/science/social science/anthropology": undefined,
    "/science/social science/history/ancient history": ['museum'],
    "/science/social science/history/archaeology": ['architecture','museum'],
    "/science/social science/history/genealogy": undefined,
    "/science/social science/history/heraldry": undefined,
    "/science/social science/history/medieval history": ['museum'],
    "/science/social science/history/modern history": ['museum'],
    "/science/social science/history/prehistory": ['museum'],
    "/science/social science/history": ['museum'],
    "/science/social science/linguistics/translation": undefined,
    "/science/social science/linguistics": undefined,
    "/science/social science/pedagogy": undefined,
    "/science/social science/philosophy/ethics": undefined,
    "/science/social science/philosophy": undefined,
    "/science/social science/sociology": undefined,
    "/science/social science": undefined,
    "/science/weather/meteorological disaster/flood": undefined,
    "/science/weather/meteorological disaster/hurricane": undefined,
    "/science/weather/meteorological disaster/tornado": undefined,
    "/science/weather/meteorological disaster": undefined,
    "/science/weather": undefined,
    "/science": undefined,
    "/shopping/auctions": undefined,
    "/shopping/classifieds": undefined,
    "/shopping/gifts/flowers": ['flowers'],
    "/shopping/gifts/greeting cards": undefined,
    "/shopping/gifts/party supplies": undefined,
    "/shopping/gifts": undefined,
    "/shopping/resources/comparisons engines": undefined,
    "/shopping/resources/consumer protection": undefined,
    "/shopping/resources/contests and freebies": undefined,
    "/shopping/resources/coupons": undefined,
    "/shopping/resources/loyalty programs": undefined,
    "/shopping/resources/product reviews": undefined,
    "/shopping/resources/warranties and service contracts": undefined,
    "/shopping/retail/department stores": undefined,
    "/shopping/retail/online stores": undefined,
    "/shopping/retail/outlet stores": undefined,
    "/shopping/retail/second-hand market": undefined,
    "/shopping/retail/wholesalers": undefined,
    "/shopping/retail": undefined,
    "/shopping/toys/action figures": undefined,
    "/shopping/toys/dolls": undefined,
    "/shopping/toys/puppets": undefined,
    "/shopping/toys/stuffed animals": undefined,
    "/shopping/toys": undefined,
    "/shopping": undefined,
    "/society/crime/drug trafficking": ['drugs'],
    "/society/crime/organized crime": undefined,
    "/society/crime/personal offense/assault": undefined,
    "/society/crime/personal offense/hate crime": undefined,
    "/society/crime/personal offense/homicide": undefined,
    "/society/crime/personal offense/human trafficking": undefined,
    "/society/crime/personal offense/kidnapping": undefined,
    "/society/crime/personal offense/torture": undefined,
    "/society/crime/property crime/arson": undefined,
    "/society/crime/property crime/bribery": undefined,
    "/society/crime/property crime/burglary": undefined,
    "/society/crime/property crime/embezzlement": undefined,
    "/society/crime/property crime/fraud": undefined,
    "/society/crime/property crime/larceny": undefined,
    "/society/crime/property crime/piracy": undefined,
    "/society/crime/property crime/robbery": undefined,
    "/society/crime/property crime/smuggling": undefined,
    "/society/crime/property crime/usury": undefined,
    "/society/crime/sexual offense/paedophilia": undefined,
    "/society/crime/sexual offense/prostitution": ['redLightDistrict'],
    "/society/crime/sexual offense/rape": ['redLightDistrict'],
    "/society/crime": undefined,
    "/society/dating": undefined,
    "/society/gay life": undefined,
    "/society/racism": undefined,
    "/society/senior living": undefined,
    "/society/sex/pornography": ['redLightDistrict'],
    "/society/sex/sex education": ['redLightDistrict'],
    "/society/sex": ['redLightDistrict'],
    "/society/social institution/divorce": undefined,
    "/society/social institution/marriage/common law marriage": undefined,
    "/society/social institution/marriage/weddings": undefined,
    "/society/social institution/marriage": undefined,
    "/society/teens": undefined,
    "/society/unrest and war": undefined,
    "/society/welfare/healthcare/hospital": undefined,
    "/society/welfare/healthcare": undefined,
    "/society/welfare/social services/volunteering": undefined,
    "/society/welfare/social services": undefined,
    "/society/welfare": undefined,
    "/society/work/contracts": undefined,
    "/society/work/retirement": undefined,
    "/society/work/unemployment": undefined,
    "/society/work/unions": undefined,
    "/society": undefined,
    "/sports/archery": undefined,
    "/sports/auto racing/nascar": undefined,
    "/sports/auto racing/rally": undefined,
    "/sports/auto racing": undefined,
    "/sports/badminton": undefined,
    "/sports/baseball": undefined,
    "/sports/basketball": undefined,
    "/sports/bicycling/mountain biking": undefined,
    "/sports/bicycling": undefined,
    "/sports/billiards": undefined,
    "/sports/boat racing": undefined,
    "/sports/bobsled": undefined,
    "/sports/bodybuilding": undefined,
    "/sports/bowling": undefined,
    "/sports/boxing": undefined,
    "/sports/canoeing and kayaking": undefined,
    "/sports/cheerleading": undefined,
    "/sports/climbing/mountain climbing": undefined,
    "/sports/climbing/rock climbing": undefined,
    "/sports/climbing": undefined,
    "/sports/cricket": undefined,
    "/sports/curling": undefined,
    "/sports/diving": undefined,
    "/sports/dog sled": undefined,
    "/sports/fencing": undefined,
    "/sports/fishing/fly fishing": undefined,
    "/sports/fishing/freshwater fishing": undefined,
    "/sports/fishing/saltwater fishing": undefined,
    "/sports/fishing/sport fishing": undefined,
    "/sports/fishing": undefined,
    "/sports/football": undefined,
    "/sports/go kart": undefined,
    "/sports/golf": undefined,
    "/sports/gymnastics/calisthenics": undefined,
    "/sports/gymnastics": undefined,
    "/sports/handball": undefined,
    "/sports/hockey/field hockey": undefined,
    "/sports/hockey": undefined,
    "/sports/horse racing": undefined,
    "/sports/horses": undefined,
    "/sports/hunting and shooting/skeet shooting": undefined,
    "/sports/hunting and shooting/target shooting": undefined,
    "/sports/hunting and shooting": undefined,
    "/sports/martial arts/judo": undefined,
    "/sports/martial arts/karate": undefined,
    "/sports/martial arts/sumo": undefined,
    "/sports/martial arts": undefined,
    "/sports/motorcycling": undefined,
    "/sports/olympics/paralympic games": undefined,
    "/sports/olympics": undefined,
    "/sports/paintball": undefined,
    "/sports/parachuting": undefined,
    "/sports/polo": undefined,
    "/sports/rodeo": undefined,
    "/sports/rowing": undefined,
    "/sports/rugby": undefined,
    "/sports/running and jogging": undefined,
    "/sports/sailing": undefined,
    "/sports/scuba diving": undefined,
    "/sports/skateboarding": undefined,
    "/sports/skating/figure skating": undefined,
    "/sports/skating/ice skating": undefined,
    "/sports/skating/roller skating": undefined,
    "/sports/skating": undefined,
    "/sports/skiing/downhill skiing": undefined,
    "/sports/skiing/nordic skiing": undefined,
    "/sports/skiing/waterskiing": undefined,
    "/sports/skiing": undefined,
    "/sports/snowboarding": undefined,
    "/sports/soccer": undefined,
    "/sports/softball": undefined,
    "/sports/sports news": undefined,
    "/sports/surfing and bodyboarding": undefined,
    "/sports/swimming": undefined,
    "/sports/table tennis and ping-pong": undefined,
    "/sports/tennis": undefined,
    "/sports/trekking": undefined,
    "/sports/volleyball/beach volleyball": undefined,
    "/sports/volleyball": undefined,
    "/sports/wakeboarding": undefined,
    "/sports/walking": undefined,
    "/sports/water polo": undefined,
    "/sports/weightlifting": undefined,
    "/sports/windsurfing": undefined,
    "/sports/wrestling": undefined,
    "/sports": undefined,
    "/style and fashion/accessories/backpacks": undefined,
    "/style and fashion/accessories/gloves": undefined,
    "/style and fashion/accessories/hats": undefined,
    "/style and fashion/accessories/scarves": undefined,
    "/style and fashion/accessories/socks": undefined,
    "/style and fashion/accessories/sunglasses": undefined,
    "/style and fashion/accessories/ties": undefined,
    "/style and fashion/accessories/wallets": undefined,
    "/style and fashion/accessories/watches": undefined,
    "/style and fashion/accessories": undefined,
    "/style and fashion/beauty/cologne": undefined,
    "/style and fashion/beauty/cosmetics/eyeshadow": undefined,
    "/style and fashion/beauty/cosmetics/lipstick": undefined,
    "/style and fashion/beauty/cosmetics/nail polish": undefined,
    "/style and fashion/beauty/cosmetics": undefined,
    "/style and fashion/beauty/cosmetology and beauty professionals": undefined,
    "/style and fashion/beauty/face and body care/body care": undefined,
    "/style and fashion/beauty/face and body care/hygiene and toiletries": undefined,
    "/style and fashion/beauty/face and body care/nail care": undefined,
    "/style and fashion/beauty/hair care": undefined,
    "/style and fashion/beauty/perfume": undefined,
    "/style and fashion/beauty/tattoos": undefined,
    "/style and fashion/body art": undefined,
    "/style and fashion/clothing/blazers": undefined,
    "/style and fashion/clothing/coats": undefined,
    "/style and fashion/clothing/hoodies": undefined,
    "/style and fashion/clothing/jackets": undefined,
    "/style and fashion/clothing/leggings": undefined,
    "/style and fashion/clothing/lingerie": undefined,
    "/style and fashion/clothing/pajamas": undefined,
    "/style and fashion/clothing/pants/jeans": undefined,
    "/style and fashion/clothing/pants": undefined,
    "/style and fashion/clothing/petticoats": undefined,
    "/style and fashion/clothing/shirts": undefined,
    "/style and fashion/clothing/shorts": undefined,
    "/style and fashion/clothing/skirts": undefined,
    "/style and fashion/clothing/sweaters": undefined,
    "/style and fashion/clothing/wedding dresses": undefined,
    "/style and fashion/clothing": undefined,
    "/style and fashion/fashion designers": undefined,
    "/style and fashion/footwear/boots": undefined,
    "/style and fashion/footwear/sandals": undefined,
    "/style and fashion/footwear/shoes": undefined,
    "/style and fashion/footwear/slippers": undefined,
    "/style and fashion/footwear/sneakers": undefined,
    "/style and fashion/footwear": undefined,
    "/style and fashion/jewelry/bracelets": undefined,
    "/style and fashion/jewelry/earrings": undefined,
    "/style and fashion/jewelry/necklaces": undefined,
    "/style and fashion/jewelry/rings": undefined,
    "/style and fashion/jewelry": undefined,
    "/style and fashion/luxury goods": undefined,
    "/style and fashion/men's fashion": undefined,
    "/style and fashion/swimwear/bikinis": undefined,
    "/style and fashion/swimwear": undefined,
    "/style and fashion/underwear": undefined,
    "/style and fashion": undefined,
    "/technology and computing/computer certification": undefined,
    "/technology and computing/computer crime": undefined,
    "/technology and computing/computer reviews": undefined,
    "/technology and computing/computer security/antivirus and malware": undefined,
    "/technology and computing/computer security/network security": undefined,
    "/technology and computing/computer security": undefined,
    "/technology and computing/consumer electronics/audio equipment/headphones": undefined,
    "/technology and computing/consumer electronics/audio equipment/speakers": undefined,
    "/technology and computing/consumer electronics/audio equipment/stereo systems and components": undefined,
    "/technology and computing/consumer electronics/audio equipment": undefined,
    "/technology and computing/consumer electronics/camera and photo equipment/binoculars": undefined,
    "/technology and computing/consumer electronics/camera and photo equipment/cameras and camcorders/camcorders": undefined,
    "/technology and computing/consumer electronics/camera and photo equipment/cameras and camcorders/camera bags": undefined,
    "/technology and computing/consumer electronics/camera and photo equipment/cameras and camcorders/camera batteries": undefined,
    "/technology and computing/consumer electronics/camera and photo equipment/cameras and camcorders/camera lenses": undefined,
    "/technology and computing/consumer electronics/camera and photo equipment/cameras and camcorders/cameras": undefined,
    "/technology and computing/consumer electronics/camera and photo equipment/telescopes": undefined,
    "/technology and computing/consumer electronics/ebook reader": undefined,
    "/technology and computing/consumer electronics/game systems and consoles/nintendo": undefined,
    "/technology and computing/consumer electronics/game systems and consoles/playstation": undefined,
    "/technology and computing/consumer electronics/game systems and consoles/xbox": undefined,
    "/technology and computing/consumer electronics/game systems and consoles": undefined,
    "/technology and computing/consumer electronics/home video and dvd": undefined,
    "/technology and computing/consumer electronics/portable entertainment": undefined,
    "/technology and computing/consumer electronics/radios": undefined,
    "/technology and computing/consumer electronics/telephones/mobile phones/smart phones": undefined,
    "/technology and computing/consumer electronics/telephones/mobile phones": undefined,
    "/technology and computing/consumer electronics/telephones": undefined,
    "/technology and computing/consumer electronics/tv and video equipment/dvrs and set-top boxes": undefined,
    "/technology and computing/consumer electronics/tv and video equipment/home theater systems": undefined,
    "/technology and computing/consumer electronics/tv and video equipment/projectors": undefined,
    "/technology and computing/consumer electronics/tv and video equipment/televisions/hdtvs": undefined,
    "/technology and computing/consumer electronics/tv and video equipment/televisions/lcd tvs": undefined,
    "/technology and computing/consumer electronics/tv and video equipment/televisions/plasma tvs": undefined,
    "/technology and computing/consumer electronics/tv and video equipment/televisions": undefined,
    "/technology and computing/consumer electronics/tv and video equipment/video players and recorders/blu-ray players and recorders": undefined,
    "/technology and computing/consumer electronics/tv and video equipment/video players and recorders/dvd players and recorders": undefined,
    "/technology and computing/consumer electronics/tv and video equipment": undefined,
    "/technology and computing/consumer electronics": undefined,
    "/technology and computing/data centers": undefined,
    "/technology and computing/electronic components": undefined,
    "/technology and computing/enterprise technology/customer relationship management": undefined,
    "/technology and computing/enterprise technology/data management": undefined,
    "/technology and computing/enterprise technology/enterprise resource planning": undefined,
    "/technology and computing/hardware/computer/desktop computer": undefined,
    "/technology and computing/hardware/computer/portable computer/laptop": undefined,
    "/technology and computing/hardware/computer/portable computer/palmtops and pdas": undefined,
    "/technology and computing/hardware/computer/portable computer/tablet": undefined,
    "/technology and computing/hardware/computer/portable computer": undefined,
    "/technology and computing/hardware/computer/servers": undefined,
    "/technology and computing/hardware/computer": undefined,
    "/technology and computing/hardware/computer components/chips and processors": undefined,
    "/technology and computing/hardware/computer components/disks": undefined,
    "/technology and computing/hardware/computer components/graphics cards": undefined,
    "/technology and computing/hardware/computer components/memory/portable": undefined,
    "/technology and computing/hardware/computer components/memory": undefined,
    "/technology and computing/hardware/computer components/motherboards": undefined,
    "/technology and computing/hardware/computer components/sound cards": undefined,
    "/technology and computing/hardware/computer networking/router": undefined,
    "/technology and computing/hardware/computer networking/wireless technology": undefined,
    "/technology and computing/hardware/computer peripherals/computer monitors": undefined,
    "/technology and computing/hardware/computer peripherals/printers, copiers and fax/copiers": undefined,
    "/technology and computing/hardware/computer peripherals/printers, copiers and fax/fax machines": undefined,
    "/technology and computing/hardware/computer peripherals/printers, copiers and fax/printers": undefined,
    "/technology and computing/hardware/computer peripherals/printers, copiers and fax/scanners": undefined,
    "/technology and computing/hardware/computer peripherals": undefined,
    "/technology and computing/hardware": undefined,
    "/technology and computing/internet technology/chat": undefined,
    "/technology and computing/internet technology/ecommerce": undefined,
    "/technology and computing/internet technology/email": undefined,
    "/technology and computing/internet technology/internet cafes": undefined,
    "/technology and computing/internet technology/isps": undefined,
    "/technology and computing/internet technology/social network": undefined,
    "/technology and computing/internet technology/web clip art": undefined,
    "/technology and computing/internet technology/web design and html": undefined,
    "/technology and computing/internet technology/web search/people search": undefined,
    "/technology and computing/internet technology/web search": undefined,
    "/technology and computing/internet technology": undefined,
    "/technology and computing/mp3 and midi": undefined,
    "/technology and computing/networking/network monitoring and management": undefined,
    "/technology and computing/networking/vpn and remote access": undefined,
    "/technology and computing/networking": undefined,
    "/technology and computing/operating systems/linux": undefined,
    "/technology and computing/operating systems/mac os": undefined,
    "/technology and computing/operating systems/unix": undefined,
    "/technology and computing/operating systems/windows": undefined,
    "/technology and computing/operating systems": undefined,
    "/technology and computing/programming languages/c and c++": undefined,
    "/technology and computing/programming languages/java": undefined,
    "/technology and computing/programming languages/javascript": undefined,
    "/technology and computing/programming languages/visual basic": undefined,
    "/technology and computing/programming languages": undefined,
    "/technology and computing/software/databases": undefined,
    "/technology and computing/software/desktop publishing": undefined,
    "/technology and computing/software/desktop video": undefined,
    "/technology and computing/software/graphics software/animation": undefined,
    "/technology and computing/software/graphics software": undefined,
    "/technology and computing/software/net conferencing": undefined,
    "/technology and computing/software/shareware and freeware": undefined,
    "/technology and computing/software": undefined,
    "/technology and computing/tech news": undefined,
    "/technology and computing/technical support": undefined,
    "/technology and computing/technological innovation": undefined,
    "/technology and computing": undefined,
    "/travel/budget travel": undefined,
    "/travel/business travel": undefined,
    "/travel/honeymoons and getaways": undefined,
    "/travel/hotels": undefined,
    "/travel/specialty travel/adventure travel": undefined,
    "/travel/specialty travel/ecotourism": undefined,
    "/travel/specialty travel/sightseeing tours": ['architecture','museum'],
    "/travel/specialty travel/vineyards": ['flowers'],
    "/travel/tourist destinations/africa": undefined,
    "/travel/tourist destinations/australia and new zealand": undefined,
    "/travel/tourist destinations/canada": undefined,
    "/travel/tourist destinations/caribbean": undefined,
    "/travel/tourist destinations/eastern europe": undefined,
    "/travel/tourist destinations/europe": undefined,
    "/travel/tourist destinations/france": undefined,
    "/travel/tourist destinations/greece": undefined,
    "/travel/tourist destinations/italy": undefined,
    "/travel/tourist destinations/japan": undefined,
    "/travel/tourist destinations/mexico and central america": undefined,
    "/travel/tourist destinations/national parks": ['flowers'],
    "/travel/tourist destinations/seaside resort": undefined,
    "/travel/tourist destinations/ski resorts": undefined,
    "/travel/tourist destinations/south america": undefined,
    "/travel/tourist destinations/spas": undefined,
    "/travel/tourist destinations/theme parks": undefined,
    "/travel/tourist destinations/united kingdom": undefined,
    "/travel/tourist destinations": undefined,
    "/travel/tourist facilities/bed and breakfast": undefined,
    "/travel/tourist facilities/camping": undefined,
    "/travel/tourist facilities/hotel": undefined,
    "/travel/transports/air travel/air and space accident": undefined,
    "/travel/transports/air travel/airfare": undefined,
    "/travel/transports/air travel/airlines": undefined,
    "/travel/transports/air travel/airplanes": undefined,
    "/travel/transports/air travel/airports": undefined,
    "/travel/transports/air travel/helicopters": undefined,
    "/travel/transports/air travel": undefined,
    "/travel/transports/public transport": undefined,
    "/travel/transports/road travel/road accident": undefined,
    "/travel/transports/sea travel/cruises": undefined,
    "/travel/transports/train travel": undefined,
    "/travel/travel agencies": undefined,
    "/travel/travel guides": undefined,
    "/travel/traveling with kids": undefined,
    "/travel/vacation rentals": undefined,
    "/travel": undefined,
};
